version: "3.5"

networks:
    gitea:
        name: gitea
        driver: bridge
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/compose-workspace/nginx/conf:/etc/nginx
      - /home/compose-workspace/nginx/logs:/var/log/nginx
      - /home/compose-workspace/nginx/html:/usr/share/nginx/html
  jenkins:
    image: "jenkins/jenkins:lts"
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/home/compose-workspace/jenkins/jenkins_home:/var/jenkins_home"
      - "/home/compose-workspace/nginx/html:/var/www"
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=10022
      - LFS_START_SERVER=false
      - DB_TYPE=sqlite3
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - '10022:10022'